export const TEST_FETCH_START = 'test_fetch_start';
export const TEST_FETCH_SUCCESS = 'test_fetch_success';
export const TEST_FETCH_FAILED = 'test_fetch_failed';
export const TEST_FETCH_RESET = 'test_fetch_reset';

// Data pass to Wizard
export const VEHICLE_DETAILS = 'VEHICLE_DETAILS';

// Utag actions
export const SEND_PAGE_DATA = 'SEND_PAGE_DATA';
export const SEND_EVENT_DATA = 'SEND_EVENT_DATA';

// monetate API
export const MONETATE_FETCH_START = 'MONETATE_FETCH_START';
export const MONETATE_FETCH_SUCCESS = 'MONETATE_FETCH_SUCCESS';
export const MONETATE_FETCH_FAILED = 'MONETATE_FETCH_FAILED';
export const MONETATE_FETCH_RESET = 'MONETATE_FETCH_RESET';

// wizard action types
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_WIZARD_PAGES_STATE = 'SET_WIZARD_PAGES_STATE';
export const CHANGE_REG_NUMBER = 'CHANGE_REG_NUMBER';
export const SET_SUBMISSION = 'SET_SUBMISSION';
export const CREATE_SUBMISSION_START = 'CREATE_SUBMISSION_START';
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS';
export const CREATE_SUBMISSION_FAIL = 'CREATE_SUBMISSION_FAIL';
export const CREATE_QUOTE_START = 'CREATE_QUOTE_START';
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS';
export const CREATE_QUOTE_FAIL = 'CREATE_QUOTE_FAIL';
export const CLEAR_LWR_QUOTE = 'CLEAR_LWR_QUOTE';
export const UPDATE_QUOTE_SUCCESS = 'UPDATE_QUOTE_SUCCESS';
export const UPDATE_QUOTE_FAIL = 'UPDATE_QUOTE_FAIL';
export const UPDATE_QUOTE_START = 'UPDATE_QUOTE_START';
export const CLEAR_UPDATE_QUOTE = 'CLEAR_UPDATE_QUOTE';
export const UPDATE_QUOTE_CLEAR = 'UPDATE_QUOTE_CLEAR';
export const RETRIEVE_QUOTE_SUCCESS = 'RETRIEVE_QUOTE_SUCCESS';
export const RETRIEVE_QUOTE_FAIL = 'RETRIEVE_QUOTE_FAIL';
export const RETRIEVE_QUOTE_START = 'RETRIEVE_QUOTE_START';
export const OFFERED_QUOTE_DETAILS = 'OFFERED_QUOTE_DETAILS';
export const MULTI_OFFERED_QUOTE_DETAILS = 'MULTI_OFFERED_QUOTE_DETAILS';
export const SET_CUSTOMIZE_SUBMISSION = 'SET_CUSTOMIZE_SUBMISSION';
export const SET_UPDATE_DDI = 'SET_UPDATE_DDI';
export const CUSTOM_UPDATE_QUOTE_SUCCESS = 'CUSTOM_UPDATE_QUOTE_SUCCESS';
export const CUSTOM_UPDATE_QUOTE_FAIL = 'CUSTOM_UPDATE_QUOTE_FAIL';
export const CUSTOM_UPDATE_QUOTE_START = 'CUSTOM_UPDATE_QUOTE_START';
export const UPDATE_QUOTE_COVERAGES_SUCCESS = 'UPDATE_QUOTE_COVERAGES_SUCCESS';
export const UPDATE_QUOTE_COVERAGES_FAIL = 'UPDATE_QUOTE_COVERAGES_FAIL';
export const SET_ADDRESS_DISPLAY = 'SET_ADDRESS_DISPLAY';
export const SET_MULTI_CUSTOMIZE_SUBMISSION = 'SET_MULTI_CUSTOMIZE_SUBMISSION';
export const MULTI_CUSTOM_UPDATE_QUOTE_START = 'MULTI_CUSTOM_UPDATE_QUOTE_START';
export const MULTI_CUSTOM_UPDATE_QUOTE_SUCCESS = 'MULTI_CUSTOM_UPDATE_QUOTE_SUCCESS';
export const MULTI_CUSTOM_UPDATE_QUOTE_FAIL = 'MULTI_CUSTOM_UPDATE_QUOTE_FAIL';
export const MULTI_CUSTOM_UPDATE_QUOTE_RESET = 'MULTI_CUSTOM_UPDATE_QUOTE_RESET';
export const INCREMENT_MC_START_DATE_PAGE = 'INCREMENT_MC_START_DATE_PAGE';
export const DECREMENT_MC_START_DATE_PAGE = 'DECREMENT_MC_START_DATE_PAGE';
export const INCREMENT_CURRENT_PAGE_INDEX = 'INCREMENT_CURRENT_PAGE_INDEX';
export const DECREMENT_CURRENT_PAGE_INDEX = 'DECREMENT_CURRENT_PAGE_INDEX';
export const RESET_CURRENT_PAGE_INDEX = 'RESET_CURRENT_PAGE_INDEX';
export const UPDATE_MULTI_QUOTE_SUCCESS = 'UPDATE_QUOTE_SUCCESS';
export const UPDATE_MULTI_QUOTE_FAIL = 'UPDATE_QUOTE_FAIL';
export const UPDATE_MULTI_QUOTE_START = 'UPDATE_QUOTE_START';
export const MULTI_QUOTE_START = 'MULTI_QUOTE_START';
export const MULTI_QUOTE_SUCCESS = 'MULTI_QUOTE_SUCCESS';
export const MULTI_QUOTE_FAIL = 'MULTI_QUOTE_FAIL';
export const MULTI_TO_SINGLE_QUOTE_START = 'MULTI_TO_SINGLE_QUOTE_START';
export const MULTI_TO_SINGLE_QUOTE_SUCCESS = 'MULTI_TO_SINGLE_QUOTE_SUCCESS';
export const MULTI_TO_SINGLE_QUOTE_FAIL = 'MULTI_TO_SINGLE_QUOTE_FAIL';
export const CLEAR_MULTI_QUOTE = 'CLEAR_MULTI_QUOTE';
export const CLEAR_MULTI_TO_SINGLE_QUOTE = 'CLEAR_MULTI_TO_SINGLE_QUOTE';

// customize quote rerate modal status
export const MARK_RERATE_MODAL_AS_DISPLAYED = 'MARK_RERATE_MODAL_AS_DISPLAYED';

export const UPDATE_MOTOR_LEGAL_ANCILLARY_SELECTION = 'UPDATE_MOTOR_LEGAL_ANCILLARY_SELECTION';
export const UPDATE_BREAKDOWN_ANCILLARY_SELECTION = 'UPDATE_BREAKDOWN_ANCILLARY_SELECTION';
export const UPDATE_PERSONAL_ACCIDENT_ANCILLARY_SELECTION = 'UPDATE_PERSONAL_ACCIDENT_ANCILLARY_SELECTION';
export const UPDATE_SUBSTITUTE_VEHICLE_ANCILLARY_SELECTION = 'UPDATE_SUBSTITUTE_VEHICLE_ANCILLARY_SELECTION';
export const UPDATE_KEY_COVER_ANCILLARY_SELECTION = 'UPDATE_KEY_COVER_ANCILLARY_SELECTION';

export const RETRIEVE_MULTICAR_QUOTE_START = 'RETRIEVE_MULTICAR_QUOTE_START';
export const RETRIEVE_MULTICAR_QUOTE_FAIL = 'RETRIEVE_MULTICAR_QUOTE_FAIL';
export const RETRIEVE_MULTICAR_QUOTE_SUCCESS = 'RETRIEVE_MULTICAR_QUOTE_SUCCESS';

export const SET_MC_SUBMISSION = 'SET_MC_SUBMISSION';
export const CREATE_MC_SUBMISSION_START = 'CREATE_MC_SUBMISSION_START';
export const CREATE_MC_SUBMISSION_SUCCESS = 'CREATE_MC_SUBMISSION_SUCCESS';
export const CREATE_MC_SUBMISSION_FAIL = 'CREATE_MC_SUBMISSION_FAIL';

export const MARK_NO_DD_MODAL_AS_DISPLAYED = 'MARK_NO_DD_MODAL_AS_DISPLAYED';
export const UPDATE_IPIDS_INFO_ANCILLARY_DOCUMENT_LINKS = 'UPDATE_IPIDS_INFO_ANCILLARY_DOCUMENT_LINKS';
export const UPDATE_BREAKDOWN_PRESELECT_ANCILLARY_SELECTION = 'UPDATE_BREAKDOWN_PRESELECT_ANCILLARY_SELECTION';
export const IPID_MATCHFORALL_START = 'IPID_MATCHFORALL_START';
export const IPID_MATCHFORALL_SUCCESS = 'IPID_MATCHFORALL_SUCCESS';
export const IPID_MATCHFORALL_FAIL = 'IPID_MATCHFORALL_FAIL';
export const IPID_DOWNLOAD_DOCUMENT_START = 'IPID_DOWNLOAD_DOCUMENT_START';
export const IPID_DOWNLOAD_DOCUMENT_FAIL = 'IPID_DOWNLOAD_DOCUMENT_FAIL';
export const IPID_MOTOR_LEGAL_DOCUMENT_SUCCESS = 'IPID_MOTOR_LEGAL_DOCUMENT_SUCCESS';
export const IPID_SUBSTITUTE_VEHICLE_DOCUMENT_SUCCESS = 'IPID_SUBSTITUTE_VEHICLE_DOCUMENT_SUCCESS';
export const IPID_PERSONAL_ACCIDENTAL_DOCUMENT_SUCCESS = 'IPID_PERSONAL_ACCIDENTAL_DOCUMENT_SUCCESS';
export const IPID_KEY_COVER_DOCUMENT_SUCCESS = 'IPID_KEY_COVER_DOCUMENT_SUCCESS';
export const IPID_BREAKDOWN_EUROPEAN_DOCUMENT_SUCCESS = 'IPID_BREAKDOWN_EUROPEAN_DOCUMENT_SUCCESS';
export const IPID_BREAKDOWN_HOMESTART_DOCUMENT_SUCCESS = 'IPID_BREAKDOWN_HOMESTART_DOCUMENT_SUCCESS';
export const IPID_BREAKDOWN_ROADSIDE_AND_RECOVERY_DOCUMENT_SUCCESS = 'IPID_BREAKDOWN_ROADSIDE_AND_RECOVERY_DOCUMENT_SUCCESS';
export const IPID_BREAKDOWN_ROADSIDE_DOCUMENT_SUCCESS = 'IPID_BREAKDOWN_ROADSIDE_DOCUMENT_SUCCESS';
export const IPID_CAR_INSURANCE_POLICY_DOCUMENT_SUCCESS = 'IPID_CAR_INSURANCE_POLICY_DOCUMENT_SUCCESS';

export const UPDATE_MARKETING_PREFERENCES_SUCCESS = 'UPDATE_MARKETING_PREFERENCES_SUCCESS';
export const UPDATE_MARKETING_PREFERENCES_FAIL = 'UPDATE_MARKETING_PREFERENCES_FAIL';
export const UPDATE_MARKETING_PREFERENCES_START = 'UPDATE_MARKETING_PREFERENCES_START';
export const CLEAR_MARKETING_PREFERENCES_DATA = 'CLEAR_MARKETING_PREFERENCES_DATA';

export const SET_BACK_NAVIGATION_DISPLAY_FLAG = 'SET_BACK_NAVIGATION_DISPLAY_FLAG';
export const SET_OBJECT_BEFORE_EDIT = 'SET_OBJECT_BEFORE_EDIT';

export const UPDATE_EPTICA_ID = 'UPDATE_EPTICA_ID';
export const UPDATE_EMAIL_SAVE_PROGRESS = 'UPDATE_EMAIL_SAVE_PROGRESS';

export const SINGLE_TO_MULTI_PRODUCT_START = 'SINGLE_TO_MULTI_PRODUCT_START';
export const SINGLE_TO_MULTI_PRODUCT_SUCCESS = 'SINGLE_TO_MULTI_PRODUCT_SUCCESS';
export const SINGLE_TO_MULTI_PRODUCT_FAIL = 'SINGLE_TO_MULTI_PRODUCT_FAIL';
export const UPDATE_MULTI_QUOTE_CLEAR = 'UPDATE_MULTI_QUOTE_CLEAR';
export const CREATE_SUBMISSION_CLEAR = 'CREATE_SUBMISSION_CLEAR';

export const MC_PAYMENT_SCHEDULE_START = 'MC_PAYMENT_SCHEDULE_START';
export const MC_PAYMENT_SCHEDULE_SUCCESS = 'MC_PAYMENT_SCHEDULE_SUCCESS';
export const MC_PAYMENT_SCHEDULE_FAIL = 'MC_PAYMENT_SCHEDULE_FAIL';

export const MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_START = 'MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_START';
export const MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_SUCCESS = 'MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_SUCCESS';
export const MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_FAIL = 'MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_FAIL';
export const MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_RESET = 'MULTI_CUSTOM_UPDATE_QUOTE_COVERAGE_RESET';

export const IPID_MC_MATCHFORALL_START = 'IPID_MC_MATCHFORALL_START';
export const IPID_MC_MATCHFORALL_SUCCESS = 'IPID_MC_MATCHFORALL_SUCCESS';
export const IPID_MC_MATCHFORALL_FAIL = 'IPID_MC_MATCHFORALL_FAIL';

export const MC_UPDATE_IPIDS_INFO_ANCILLARY_DOCUMENT_LINKS = 'MC_UPDATE_IPIDS_INFO_ANCILLARY_DOCUMENT_LINKS';

export const UPDATE_MC_MOTOR_LEGAL_ANCILLARY_SELECTION = 'UPDATE_MC_MOTOR_LEGAL_ANCILLARY_SELECTION';
export const UPDATE_MC_BREAKDOWN_ANCILLARY_SELECTION = 'UPDATE_MC_BREAKDOWN_ANCILLARY_SELECTION';
export const UPDATE_MC_PERSONAL_ACCIDENT_ANCILLARY_SELECTION = 'UPDATE_MC_PERSONAL_ACCIDENT_ANCILLARY_SELECTION';
export const UPDATE_MC_SUBSTITUTE_VEHICLE_ANCILLARY_SELECTION = 'UPDATE_MC_SUBSTITUTE_VEHICLE_ANCILLARY_SELECTION';
export const UPDATE_MC_KEY_COVER_ANCILLARY_SELECTION = 'UPDATE_MC_KEY_COVER_ANCILLARY_SELECTION';
export const UPDATE_MC_BREAKDOWN_PRESELECT_ANCILLARY_SELECTION = 'UPDATE_MC_BREAKDOWN_PRESELECT_ANCILLARY_SELECTION';

export const MC_UPDATE_MARKETING_PREFERENCES_SUCCESS = 'MC_UPDATE_MARKETING_PREFERENCES_SUCCESS';
export const MC_UPDATE_MARKETING_PREFERENCES_FAIL = 'MC_UPDATE_MARKETING_PREFERENCES_FAIL';
export const MC_UPDATE_MARKETING_PREFERENCES_START = 'MC_UPDATE_MARKETING_PREFERENCES_START';
export const MC_CLEAR_MARKETING_PREFERENCES_DATA = 'MC_CLEAR_MARKETING_PREFERENCES_DATA';
export const MC_CLEAR_MARKETING_PREFERENCES_RESET = 'MC_CLEAR_MARKETING_PREFERENCES_RESET';
export const MC_MILESETONE_EDIT = 'MC_MILESETONE_EDIT';

export const MULTI_TO_SINGLE_RESET = 'MULTI_TO_SINGLE_RESET';
